/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.flashcards;

import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.util.ArrayList;
import javax.swing.Box;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTextField;

/**
 *
 * @author uygun
 */

public class EditScreen extends javax.swing.JFrame {

    /**
     * Creates new form EditScreen
     */
    
    public static File theFile;
    private String fileName;
    private int index;
    
    public EditScreen() {
        initComponents();      
        wordTextField.setEditable(false);
        definitionTextField.setEditable(false);
        previousButton.setEnabled(false);
        nextButton.setEnabled(false);
        deleteButton.setEnabled(false);
        addButton.setEnabled(false);
        theFile = null;
        fileName = "";
        index = 0;
    }
    
    String[] wordAndDef = new String[2];
    
    public ArrayList<String[]> listOfWords = new ArrayList<String[]>();
    //public ArrayList<String[]> editedList = new ArrayList<String[]>();
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFileChooser1 = new javax.swing.JFileChooser();
        buttonGroup = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        chooseFileButton = new javax.swing.JButton();
        saveButton = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        wordTextField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        definitionTextField = new javax.swing.JTextField();
        nextButton = new javax.swing.JButton();
        previousButton = new javax.swing.JButton();
        wordRadioButton = new javax.swing.JRadioButton();
        definitionRadioButton = new javax.swing.JRadioButton();
        jLabel5 = new javax.swing.JLabel();
        deleteButton = new javax.swing.JButton();
        doneButton = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        editTextArea = new javax.swing.JTextArea();
        cancelButton = new javax.swing.JButton();
        addButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Edit a Study Set");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel2.setText("Set");

        chooseFileButton.setText("Choose a file");
        chooseFileButton.setMaximumSize(new java.awt.Dimension(93, 23));
        chooseFileButton.setMinimumSize(new java.awt.Dimension(93, 23));
        chooseFileButton.setPreferredSize(new java.awt.Dimension(93, 23));
        chooseFileButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chooseFileButtonActionPerformed(evt);
            }
        });

        saveButton.setText("Save ");
        saveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveButtonActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel3.setText("Word");

        wordTextField.setBackground(new java.awt.Color(204, 204, 204));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel4.setText("Definition");

        definitionTextField.setBackground(new java.awt.Color(204, 204, 204));

        nextButton.setText("Next");
        nextButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextButtonActionPerformed(evt);
            }
        });

        previousButton.setText("Previous");
        previousButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                previousButtonActionPerformed(evt);
            }
        });

        buttonGroup.add(wordRadioButton);
        wordRadioButton.setText("Word");
        wordRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                wordRadioButtonActionPerformed(evt);
            }
        });

        buttonGroup.add(definitionRadioButton);
        definitionRadioButton.setText("Definition");

        jLabel5.setText("Edit:");

        deleteButton.setText("Delete this word");
        deleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteButtonActionPerformed(evt);
            }
        });

        doneButton.setText("Done");
        doneButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                doneButtonActionPerformed(evt);
            }
        });

        editTextArea.setColumns(10);
        editTextArea.setLineWrap(true);
        editTextArea.setRows(5);
        jScrollPane2.setViewportView(editTextArea);

        cancelButton.setText("Cancel");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        addButton.setText("Add word");
        addButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(definitionTextField, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(previousButton, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(nextButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(wordTextField, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(chooseFileButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(wordRadioButton)
                                        .addGap(18, 18, 18)
                                        .addComponent(definitionRadioButton)))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(deleteButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(addButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(doneButton))
                        .addGap(21, 21, 21))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(cancelButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(saveButton)
                        .addGap(22, 22, 22))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(chooseFileButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(wordTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(definitionTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4)))
                    .addComponent(jScrollPane2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(previousButton)
                    .addComponent(nextButton)
                    .addComponent(doneButton))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(definitionRadioButton)
                    .addComponent(jLabel5)
                    .addComponent(wordRadioButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(deleteButton, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(saveButton)
                    .addComponent(cancelButton)
                    .addComponent(addButton, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nextButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextButtonActionPerformed
        // TODO add your handling code here:
        if(index+1<=listOfWords.size()-1){
            index++;
            String[] currentListIndex = listOfWords.get(index);
            wordTextField.setText(currentListIndex[0]);
            definitionTextField.setText(currentListIndex[1]);
        }
    }//GEN-LAST:event_nextButtonActionPerformed

    private void chooseFileButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chooseFileButtonActionPerformed
        // TODO add your handling code here:
        int value = jFileChooser1.showOpenDialog(null);
        if(value == jFileChooser1.APPROVE_OPTION){
            theFile = new File(jFileChooser1.getSelectedFile().getAbsolutePath());
            fileName = theFile.getName();
            chooseFileButton.setText(fileName);
        }
        listOfWords = getWordsList();
        String[] currentListIndex = listOfWords.get(index);
        wordTextField.setText(currentListIndex[0]);
        definitionTextField.setText(currentListIndex[1]);
        previousButton.setEnabled(true);
        nextButton.setEnabled(true);
        deleteButton.setEnabled(true);
        addButton.setEnabled(true);
    }//GEN-LAST:event_chooseFileButtonActionPerformed

    private void previousButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_previousButtonActionPerformed
        // TODO add your handling code here:
        if(index-1>=0){
            index--;
            String[] currentListIndex = listOfWords.get(index);
            wordTextField.setText(currentListIndex[0]);
            definitionTextField.setText(currentListIndex[1]);
        }
    }//GEN-LAST:event_previousButtonActionPerformed

    private void doneButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_doneButtonActionPerformed
        // TODO add your handling code here:
        if(!"".equals(editTextArea.getText())){
            editWordsList(listOfWords);
            editTextArea.setText("");
            buttonGroup.clearSelection();
        }
    }//GEN-LAST:event_doneButtonActionPerformed

    private void deleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteButtonActionPerformed
        // TODO add your handling code here:
        listOfWords.remove(listOfWords.get(index));
        index--;
        wordTextField.setText(listOfWords.get(index)[0]);
        definitionTextField.setText(listOfWords.get(index)[1]);
    }//GEN-LAST:event_deleteButtonActionPerformed

    private void saveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveButtonActionPerformed
        // TODO add your handling code here:
        overwriteToFile(listOfWords);
        int theOption = JOptionPane.showOptionDialog(null,
            "Are you sure you want to save changes to " + fileName + "?", "Save Changes",
            JOptionPane.DEFAULT_OPTION, JOptionPane.WARNING_MESSAGE, null, new String[] {"Yes", "No"}, "No");
            if (theOption == 0){
                JOptionPane.getRootFrame().dispose();
                this.dispose();
                new MainMenu().setVisible(true);
            }
    }//GEN-LAST:event_saveButtonActionPerformed

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        // TODO add your handling code here:
         int theOption = JOptionPane.showOptionDialog(null,
            "Are you sure you want to go back to the main menu? ", "Cancel",
            JOptionPane.DEFAULT_OPTION, JOptionPane.WARNING_MESSAGE, null, new String[] {"Yes", "No"}, "No");
            if (theOption == 0){
                JOptionPane.getRootFrame().dispose();
                this.dispose();
                new MainMenu().setVisible(true);
            }
    }//GEN-LAST:event_cancelButtonActionPerformed

    private void wordRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_wordRadioButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_wordRadioButtonActionPerformed

    private void addButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addButtonActionPerformed
        // TODO add your handling code here:
        JTextField wordField = new JTextField(10);
        JTextField defField = new JTextField(10);

        JPanel myPanel = new JPanel();
        myPanel.add(new JLabel("Word:"));
        myPanel.add(wordField);
        myPanel.add(Box.createHorizontalStrut(10)); // a spacer
        myPanel.add(new JLabel("Definition:"));
        myPanel.add(defField);
       
        Boolean isInputValid = false;
        do{
            int result = JOptionPane.showConfirmDialog(null, myPanel, 
                "Please Enter Word and Definition", JOptionPane.OK_CANCEL_OPTION);
            if(result == JOptionPane.OK_OPTION){
                if(wordField.getText().equals("") || defField.getText().equals("")){
                    int theOption = JOptionPane.showOptionDialog(null,
                    "Please enter a valid word and definition. ", "Invalid Input",
                    JOptionPane.DEFAULT_OPTION, JOptionPane.WARNING_MESSAGE, null, new String[] {"Ok"}, "Ok");
                    if (theOption == 0){
                        JOptionPane.getRootFrame().dispose();
                    }
                }else if(!wordField.getText().equals("") && !defField.getText().equals("")){
                    String newWord = wordField.getText();
                    String newDef = defField.getText();
                    String[] newWordAndDef = {newWord, newDef};
                    listOfWords.add(newWordAndDef);
                    isInputValid = true;
                }
            }else{
                isInputValid = true;
            }
        }while(!isInputValid);  
    }//GEN-LAST:event_addButtonActionPerformed

    private ArrayList getWordsList(){
        try{
            File wordsFile = theFile;
            FileReader fr = new FileReader(wordsFile);
            BufferedReader br = new BufferedReader(fr);
            String line = br.readLine();
            listOfWords.clear();
    
            while(line != null){ 
                wordAndDef = line.split("\te23bf0hj\t");
                listOfWords.add(wordAndDef);
                line = br.readLine();
                if(line.equals("29rje2r9")){
                    line = br.readLine();
                }
            }
            br.close();
            fr.close();
        }catch(FileNotFoundException e){
            System.out.println("An error occurred. File not found");
        }catch(IOException e2){
            System.out.println("IO exception thrown.");
        }
        return listOfWords;
    }

    private ArrayList editWordsList(ArrayList<String[]> listOfWords){
        if(wordRadioButton.isSelected()){
            listOfWords.get(index)[0] = editTextArea.getText();
            wordTextField.setText(listOfWords.get(index)[0]);
        }else if(definitionRadioButton.isSelected()){
            listOfWords.get(index)[1] = editTextArea.getText();
            definitionTextField.setText(listOfWords.get(index)[1]);
        }
        return listOfWords;
    }
 
    private void overwriteToFile(ArrayList<String[]> listOfWords){
        try{
            FileWriter fw = new FileWriter(theFile);
            BufferedWriter bw = new BufferedWriter(fw);
            //Writer fileWriter = new FileWriter(theFile);
            for(int i=0; i<listOfWords.size(); i++){
                bw.write(listOfWords.get(i)[0] + "\te23bf0hj\t" + listOfWords.get(i)[1]);
                bw.write("\n29rje2r9\n");
            }
            bw.close();
            fw.close();
        }catch(FileNotFoundException e){
          System.out.println("An error occurred. File not found");
          e.printStackTrace();
        }catch(IOException e2){
          System.out.println("IO exception thrown.");
          e2.printStackTrace();
        }   
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EditScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EditScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EditScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EditScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EditScreen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addButton;
    private javax.swing.ButtonGroup buttonGroup;
    private javax.swing.JButton cancelButton;
    private javax.swing.JButton chooseFileButton;
    private javax.swing.JRadioButton definitionRadioButton;
    private javax.swing.JTextField definitionTextField;
    private javax.swing.JButton deleteButton;
    private javax.swing.JButton doneButton;
    private javax.swing.JTextArea editTextArea;
    private javax.swing.JFileChooser jFileChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton nextButton;
    private javax.swing.JButton previousButton;
    private javax.swing.JButton saveButton;
    private javax.swing.JRadioButton wordRadioButton;
    private javax.swing.JTextField wordTextField;
    // End of variables declaration//GEN-END:variables
}
